# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dexter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '12.0'

  # Pods for Dexter
  pod 'MaterialComponents/ActivityIndicator'
  pod 'MaterialComponents/Snackbar'
  pod 'Kingfisher', '~> 5.0'

  target 'DexterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DexterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
